### ISSUE TITLE
Full screen causing issues

### ISSUE THREAD

**Issue by jacblo** [hermes83/compiz-windows-effect-cinnamon#1]
I love the idea of this extension and how it replaces the one that leaves artifacts that is built in on the extension manager in cinnamon. But every time i press the button (in the corner next to the place to close the window) to make it reach the edges of the screen, the window goes crazy for a second because of the wobble effect. the same thing happens in the reverse when shrinking the window.
Sometimes it's more pronounced than other times so i recorded one.

There should be a way to disable the wobble for expanding and shrinking windows - like either make it default or have a setting if some people want this for some reason...

![image](https://user-images.githubusercontent.com/68179224/176138188-c25475c1-0222-4795-93c1-0a379792b47b.png)
![test](https://user-images.githubusercontent.com/68179224/176138655-6f93402e-c698-40ed-82a6-40f79c1fb211.gif)

**Comment by hermes83** [comment]
Hello
First I want to thank you for your interest in the extension.
What you report is not strange behavior, but it is how the original Compiz effect works. You can see it in action in old youtube shoots, such as this one:

[https://www.youtube.com/watch?v=USedxVrU2Ko](https://www.youtube.com/watch?v=USedxVrU2Ko)

I preferred to solve your need with a different approach. Instead of introducing a checkbox I have added a slidebar that allows you to set the "amount of the effect" when maximizing and de-maximizing a window:

![immagine](https://user-images.githubusercontent.com/7895800/176243688-02cac434-1c27-4f7a-903a-e45ddb1af599.png)

If you want disable it than simply put this value to 0
